server {
    listen 8081;
    server_name localhost;

    location / {
        proxy_pass https://psrc-4kk0p.westeurope.azure.confluent.cloud;
        proxy_ssl_server_name on;

        proxy_set_header Host psrc-4kk0p.westeurope.azure.confluent.cloud;
        proxy_set_header Authorization "Basic WEdPU1NZTkxNVUFUTDZSUTpjZmx0bmk5WGluajV5ZVZVVDNtRVVsQXpKZGJWU1EwN3VvK0ppeHJsOEZVSHZJaTBGLzBZYUMvL2h4b1NUTkdB";
        proxy_set_header Content-Type $content_type;
        proxy_set_header Accept $http_accept;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
